[package]
name = "jacopone"
version = "0.1.0"
authors = ["zeegomo <g.pasini98@gmail.com>"]

[dependencies]
clap = { version = "2.33.0", features = ["yaml"]}
jacopone = { git = "https://github.com/Zeegomo/jacopone-lib"}
